// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PslibThesesBackend.Models;

namespace PslibThesesBackend.Migrations
{
    [DbContext(typeof(ThesesContext))]
    [Migration("20190922130823_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PslibThesesBackend.Models.Idea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Participants");

                    b.Property<string>("Resources");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Subject");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Ideas");
                });

            modelBuilder.Entity("PslibThesesBackend.Models.IdeaGoal", b =>
                {
                    b.Property<int>("IdeaId");

                    b.Property<int>("Order");

                    b.Property<string>("Text")
                        .IsRequired();

                    b.HasKey("IdeaId", "Order");

                    b.ToTable("IdeaGoals");
                });

            modelBuilder.Entity("PslibThesesBackend.Models.IdeaOutline", b =>
                {
                    b.Property<int>("IdeaId");

                    b.Property<int>("Order");

                    b.Property<string>("Text")
                        .IsRequired();

                    b.HasKey("IdeaId", "Order");

                    b.ToTable("IdeaOutlines");
                });

            modelBuilder.Entity("PslibThesesBackend.Models.IdeaTarget", b =>
                {
                    b.Property<int>("IdeaId");

                    b.Property<int>("TargetId");

                    b.HasKey("IdeaId", "TargetId");

                    b.HasIndex("TargetId");

                    b.ToTable("IdeaTarget");
                });

            modelBuilder.Entity("PslibThesesBackend.Models.Target", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RGB");

                    b.Property<string>("Text")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Targets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RGB = -256,
                            Text = "MP Lyceum"
                        },
                        new
                        {
                            Id = 2,
                            RGB = -23296,
                            Text = "RP Lyceum"
                        },
                        new
                        {
                            Id = 3,
                            RGB = -65536,
                            Text = "MP IT"
                        },
                        new
                        {
                            Id = 4,
                            RGB = -16776961,
                            Text = "MP Strojírenství"
                        },
                        new
                        {
                            Id = 5,
                            RGB = -16744448,
                            Text = "MP Elektrotechnika"
                        });
                });

            modelBuilder.Entity("PslibThesesBackend.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<int>("Gender");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("MiddleName");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "1111-1111-1111",
                            Email = "michal.stehlik@pslib.cz",
                            FirstName = "Michal",
                            Gender = 0,
                            LastName = "Stehlík"
                        },
                        new
                        {
                            Id = "1111-1111-1112",
                            Email = "ot@drtina.cz",
                            FirstName = "Otmar",
                            Gender = 0,
                            LastName = "Drtina"
                        });
                });

            modelBuilder.Entity("PslibThesesBackend.Models.Idea", b =>
                {
                    b.HasOne("PslibThesesBackend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PslibThesesBackend.Models.IdeaGoal", b =>
                {
                    b.HasOne("PslibThesesBackend.Models.Idea", "Idea")
                        .WithMany("Goals")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PslibThesesBackend.Models.IdeaOutline", b =>
                {
                    b.HasOne("PslibThesesBackend.Models.Idea", "Idea")
                        .WithMany("Outlines")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PslibThesesBackend.Models.IdeaTarget", b =>
                {
                    b.HasOne("PslibThesesBackend.Models.Idea", "idea")
                        .WithMany("Targets")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PslibThesesBackend.Models.Target", "Target")
                        .WithMany("Ideas")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
